name: Build & test
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        framework: [ 'net8.0', 'net9.0' ]
        configuration: [ 'Debug', 'Release' ]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - run: dotnet restore

      - run: dotnet build --no-restore --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }}

      - run: dotnet test --no-build --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }} --logger trx --results-directory ./TestResults

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: "./TestResults"
          name: "TestResults-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}"
